### ISSUE TITLE
Workspace Name to be include 

### ISSUE THREAD

**Issue by RicardoAfonsoPedro** [tirnovar/Power-BI-Admin-REST-API-Connector#3]
Hi, Love the solution was exactly what I was looking for to manage the power bi administration.
Will be possible to include in the solution also the workspace name? 
Thank you

**Comment by RicardoAfonsoPedro** [comment]
Found it in the Groups folder :)
Will be good to rename it  as you have in your structure ( Groups & Workspaces )
Thank you for this amazing solution :)

**Comment by tirnovar** [comment]
Hey, Yes. Officially in the case of their API, it is called Groups, but it is an excellent idea to change the name in this doc to have it as Groups & Workspaces. I will do it
