### ISSUE TITLE
No Issues ( Request Question )

### ISSUE THREAD

**Issue by RicardoAfonsoPedro** [tirnovar/Power-BI-Admin-REST-API-Connector#8]
Hi Štěpán Rešl, 
I hope you are well and thank you again for this fantastic tool.
Like to ask you if are you planning to had also the Domains so we are able to identify the workspaces that are live in the Finance Domain, HR Domain Etc...?
Also, the Contact list from the workspace will be very useful.
Looking forward to ear from you.
Thank you 
Ricardo

**Comment by tirnovar** [comment]
Hello,

Indeed. I will add Domains soon. Unfortunately, you receive domain ID in the case of workspaces only if you ask for workspace details through Scanner API

**Comment by logonnaidoo2020** [comment]
Hello
Have you found the issue why it hangs sometimes. When will you a newer version of this API

**Comment by tirnovar** [comment]
Hey, unfortunately, I am not working on the domain right now. Once I finish my PySpark solution for the same, I will return it to this connector and add it.

**Comment by tirnovar** [comment]
Hey, I have just published new package with connector, that supports Domains.

**Comment by RicardoAfonsoPedro** [comment]
Hello, Thank you for the update :) looking forward to put in practise.

**Comment by logonnaidoo0** [comment]
Thank you for the update. Can you confirm if connector is going to be Microsoft Certified?

**Comment by tirnovar** [comment]
No. This connector will not be certified.

**Comment by logonnaidoo0** [comment]
Thanks for the update
